### ISSUE TITLE
add everyone's affiliations

### ISSUE THREAD

**Issue by jovo** [shachen/PLDS#70]
mine are:

Dept BME
Institute for Computational Medicine
both JHU

AND

Child Mind Institute

and i have a middle initial T.

**Comment by vincentliuk** [comment]
Kai Liu:
Department of Neuroscience, Johns Hopkins University, Baltimore, ,Maryland,
USA

On Mon, Jul 13, 2015 at 10:02 AM, joshua vogelstein <
notifications@github.com> wrote:

> mine are:
>
> Dept BME
> Institute for Computational Medicine
> both JHU
>
> AND
>
> Child Mind Institute
>
> and i have a middle initial T.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shachen/PLDS/issues/70>.
>



-- 
Liu, Kai
Ph.D Candidate
Seth Blackshaw Lab
Department of Neuroscience
The Johns Hopkins University School of Medicine
Email: kliu27@jhu.edu

**Comment by yangyutu** [comment]
Yuguang Yang:
Department of Chemical and Biomolecular Engineering, Johns Hopkins
University, Baltimore, ,Maryland,
USA
Thank you.

**Comment by xuyuting** [comment]
Yuting Xu:
Department of Biostatistics, 
Johns Hopkins Bloomberg School of Public Health
