### ISSUE TITLE
update text to reflect new times

### ISSUE THREAD

**Issue by jovo** [shachen/PLDS#75]
in particular, re-run results for Table 1.

also, in Section 3.5, add a sentence about your new tricks, eg, pre-computing some stuff.

@yangyutu

**Comment by jovo** [comment]
@yangyutu @vincentliuk did this happen yet?

**Comment by yangyutu** [comment]
Hello, Josh,

Sorry for the late. As a fair comparison, we finally asked some friends to
use public health cluster, the same as Shaojie use to get those data. Now I
am struggling with the tex compiler. I am fixing my TexMaker now. The
update should be online very soon.

Thank you.

**Comment by yangyutu** [comment]
updated.
